site_name: jupyterlab-sql-editor
site_url: https://cybercentrecanada.github.io/jupyterlab-sql-editor
site_dir: site
nav:
  - Home: index.md
  - sparksql magic: sparksql.md
  - trino magic: trino.md
  - Notebook: example/SparkSyntaxDemo.ipynb
theme:
  name: material
plugins:
  - search
  - mkdocs-jupyter:
      execute: false
